### ISSUE TITLE
The results of ADE20K

### ISSUE THREAD

**Issue by linfangjian01** [facebookresearch/ConvNeXt#1]
We found a problem that in the ADE20k dataset test, BEiT defaults to the 'whole' test, but the 'slide' test standby is here, so there should be test_cfg = dict(mode='slide', crop_size=crop_size, stride=(341, 341)) in the config.

**Comment by MengzhangLI** [comment]
Hi, thanks for your excellent work.

The config files made be slightly modified to slide mode in `test_cfg`. Thus the results of provided models could be aligned.

**Comment by s9xie** [comment]
Thank you @MengzhangLIand @linfangjian01. You both are right. @HannaMao just pushed a commit that separates the multi-scale testing and single-scale testing to avoid the confusion. For multi-scale testing, the test_mode is 'whole', so it's identical to Swin's strategy and the results are comparable. For single-scale testing, we followed BEiT to use 'slide', and the results are presented in Appendix (but they are not directly comparable to Swin's single-scale numbers due to the difference in test mode).
