### ISSUE TITLE
Will the ImageNet 22k pretrained models of 384x384 be released?

### ISSUE THREAD

**Issue by SlongLiu** [facebookresearch/ConvNeXt#3]
Hi, 

Thanks for the excellent work that presents the best backbone for vision l believe. I like the detailed analysis and discussions in the paper as well.  I wonder if the 384x384 models of ConvNeXt-L and ConvNeXt-XL that pretrained on ImageNet22k be made available?

**Comment by s9xie** [comment]
Hi, thank you for the question. To clarify: we only pre-train on ImageNet 22k dataset using the 224x224 resolution.  We only train with 384x384 resolution when fine-tuning on ImageNet-1K.

That's why there's only one pre-trained checkpoint (ImageNet-22K / 224x224) for L and XL models. 
I hope this is helpful.

**Comment by yonger001** [comment]
Hi, is there any plan to released 384x384 models of ConvNeXt-B ? Looking forward your reply.
